#     =====================================================================
#     |       BossMessage - by Victor2748 (Pixelized Network)             |
#     |       http://dev.bukkit.org/bukkit-plugins/bossmessage/           |
#     |-------------------------------------------------------------------|
#     |                          DO NOT TOUCH:                            |
#     |                  '- ==: ConfigurationMessage'                     |
#     |                               AND                                 |
#     |                         'ConfigVersion'                           |
#     |                  OR IT WILL BREAK YOUR CONFIG!!!                  |
#     =====================================================================

BossMessage:
  Random: false
  ColorCodes: 1234567890abcdef
  NoPermission: '&cNo Permission!'
  Broadcast:
    DefaultTime: 30
    Percent: auto
  Schedule:
    DefaultTime: 60
    Percent: auto
  CheckUpdates: true
  Whitelist: false
  RepeatRandomColors: true
  RepeatRandomPlayers: true
  VanishNoPacketSupport: false
  Messages: {}
  WhitelistedWorlds:
  - world
  - world_nether
  - ExampleWorld
  IgnoredPlayers: []
  Tasks: {}
  Regions: {}
  Events:
    PlayerDeathByPlayer:
      Enabled: true
      Message: '&ePlayer &a%victim% &ewas killed by &c%killer%'
      Percent: auto
      Show: 100
      Broadcast: EVERYONE
  ConfigVersion: 0
