#     =====================================================================
#     |       BossMessage - by Victor2748 (Pixelized Network)             |
#     |       IP: play.pixelizedmc.net                                    |
#     |       Website: Pixelizedmc.net                                    |
#     |       http://dev.bukkit.org/bukkit-plugins/bossmessage/           |
#     |-------------------------------------------------------------------|
#     |                      DO NOT TOUCH THE LINE:                       |
#     |                     '- ==: Message'                               |
#     |                  OR IT WILL BREAK YOUR CONFIG!!!                  |
#     =====================================================================

BossMessage:
  Random: false
  ColorCodes: 1234567890abcdef
  NoPermission: '&cNo Permission!'
  Broadcast:
    DefaultTime: 30
    Percent: auto
  CheckUpdates: true
  Whitelist: false
  RepeatRandomColors: true
  RepeatRandomPlayers: true
  VanishNoPacketSupport: false
  Messages: {}
  WhitelistedWorlds:
  - world
  - world_nether
  - ExampleWorld
  IgnoredPlayers: []
  ConfigVersion: 0
