name: BossMessage
version: 1.3.0
authors: [michidk]

main: net.PixelizedMC.BossMessage.Main

commands:
  BossMessage:
    description: main command
    usage: /<command>
    aliases: [bm, bmessage]

depend: [BarAPI]