name: BossMessage
version: 2.0
author: victor2748
main: net.pixelizedmc.bossmessage.Main
depend: [BarAPI]
softdepend: [Vault, VanishNoPacket, WorldGuard, WGRegionEvents]
commands:
  BossMessage:
    description: Main BossMessage Command
    aliases: [bm, bmessage]
permissions:
  bossmessage.info:
    description: Permission to see the info
    default: true
  bossmessage.toggle:
    description: Permission to toggle your message view
    default: true
  bossmessage.see.default:
    description: Permission to see messages from default group
    default: true
  bossmessage.user:
    description: Permission to be a user
    default: true