name: BossMessage
version: 1.3
authors: [victor2748, michidk]
main: net.PixelizedMC.BossMessage.Main
depend: [BarAPI]
commands:
  BossMessage:
    description: main command
    aliases: [bm, bmessage]
permissions:
  bossmessage.admin:
    default: op
    children:
      bossmessage.reload: true
      bossmessage.add: true
      bossmessage.remove: true
      bossmessage.list: true
      bossmessage.interval: true
      bossmessage.show: true
      bossmessage.see: true
  bossmessage.*:
    default: op
    children:
      bossmessage.reload: true
      bossmessage.add: true
      bossmessage.remove: true
      bossmessage.list: true
      bossmessage.interval: true
      bossmessage.show: true
      bossmessage.see: true
  bossmessage.add:
    description: Permission to add messages
  bossmessage.see:
    description: Permission to see messages
  bossmessage.remove:
    description: Permission to remove messages
  bossmessage.list:
    description: Permission to list messages
  bossmessage.interval:
    description: Permission to set interval
  bossmessage.show:
    description: Permission to set show time
  bossmessage.reload:
    description: Permission to reload the plugin