name: BossMessage
version: 1.5
authors: [victor2748, michidk]
main: net.PixelizedMC.BossMessage.Main
depend: [BarAPI]
commands:
  BossMessage:
    description: Main BossMessage Command
    aliases: [bm, bmessage]
permissions:
  bossmessage.admin:
    default: op
    children:
      bossmessage.reload: true
      bossmessage.add: true
      bossmessage.remove: true
      bossmessage.list: true
      bossmessage.see: true
      bossmessage.whitelist: true
      bossmessage.rrc: true
      bossmessage.random: true
      bossmessage.addworld: true
      bossmessage.delworld: true
      bossmessage.setcolors: true
      bossmessage.noperm: true
      bossmessage.exemptrdm: true
      bossmessage.toggle: true
  bossmessage.*:
    default: op
    children:
      bossmessage.reload: true
      bossmessage.add: true
      bossmessage.remove: true
      bossmessage.list: true
      bossmessage.interval: true
      bossmessage.see: true
      bossmessage.whitelist: true
      bossmessage.rrc: true
      bossmessage.random: true
      bossmessage.addworld: true
      bossmessage.delworld: true
      bossmessage.setcolors: true
      bossmessage.noperm: true
      bossmessage.exemptrdm: true
      bossmessage.toggle: true
  bossmessage.add:
    description: Permission to add messages
  bossmessage.addworld:
    description: Permission to add worlds to whitelist
  bossmessage.exemptrdm:
    description: Permission to be exempted from %rdm_player% tag
  bossmessage.noperm:
    description: Permission to set the NoPermission message
  bossmessage.setcolors:
    description: Permission to set the random color list
  bossmessage.delworld:
    description: Permission to remove worlds from whitelist
  bossmessage.random:
    description: Permission to toggle random message picking
  bossmessage.rrc:
    description: Permission to toggle random color repeating
  bossmessage.whitelist:
    description: Permission to toggle the whitelist
  bossmessage.see:
    description: Permission to see messages
    default: true
  bossmessage.toggle:
    description: Permission to toggle your message view
    default: true
  bossmessage.remove:
    description: Permission to remove messages
  bossmessage.list:
    description: Permission to list messages
  bossmessage.reload:
    description: Permission to reload the plugin